name: Detect Changed File

on:
  push:
    branches:
      - main

jobs:
  detect-and-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Detect changed file
        shell: bash
        run: |
          git fetch origin ${{ github.base_ref }} --depth=1
          CHANGED=$(git diff --name-only origin/${{ github.base_ref }})
          
          echo "ðŸ”Ž Changed files:"
          echo "$CHANGED"

          sh_files=$(echo "$CHANGED" | grep '\.sh$' || true)
          py_files=$(echo "$CHANGED" | grep '\.py$' || true)
          ps1_files=$(echo "$CHANGED" | grep '\.ps1$' || true)
